---
- name: Add web server IP addresses to load balancer
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Add IP addresses to load balancer
      ansible.builtin.debug:
        msg: |
          Adding the {{ item }} host to the load balancer
      loop: "{{ vm_names }}"
      loop_control:
        label: "{{ item }}"