---
- name: Remove web server IP addresses from load balancer
  hosts: localhost
  gather_facts: no
  tasks:
    - name: remove hosts from load balancer
      ansible.builtin.debug:
        msg: |
          Removing hosts from the load balancer:
          {% for fqdn in vm_names %}
          - {{ fqdn }}
          {% endfor %}

    - name: Link to Example Citrix LB Code
      ansible.builtin.debug:
        msg: |
          Example Citrix LB Code: https://github.com/shadowman-lab/Ansible-Citrix/blob/main/roles/citrix_remove/tasks/main.yml
