---
- name: Update ServiceNow Change Request
  hosts: localhost
  gather_facts: no
  tasks:

    - name: Display the ITSM update message from workflow
      ansible.builtin.debug:
        msg: |
          ITSM Update Summary:
          {{ remove_vm }} {{ itsm_update_message }}

          See examples in comments on github: https://github.com/mkbredem/aap_tfc_workshop/blob/main/servicenow_catalog_update.yml

