---
- name: Remove ServiceNow CMDB Record
  hosts: localhost
  gather_facts: no
  tasks:

    - name: Set CMDB data to send to ServiceNow
      set_fact:
        cmdb_data:
          name: "{{ inventory_hostname }}"
          fqdn: "{{ ansible_fqdn | default(inventory_hostname) }}"
          ip_address: "{{ ansible_default_ipv4.address }}"
          os: "{{ ansible_distribution }} {{ ansible_distribution_version }}"
          u_application: "web_app_1"
          install_status: "1"  # Installed
          short_description: "Provisioned with web_app_1 application"

    - name: Print CMDB record to be created
      debug:
        var: cmdb_data

#    - name: Remove SNOW CMDB Record
#      servicenow.itsm.configuration_item:
#        state: absent
#        asset_tag: "{{ owner | default(omit) }}"
#        name: "{{ inventory_hostname }}"
#        ip_address: "{{ ip_addr | default(omit) }}"
#        sys_class_name: cmdb_ci_server
#        sys_id: "{{ sys_id | default(omit) }}"
#        other:
#          classification: "{{ env | default(omit) }}"
#          fqdn: "{{ fqdn | default(omit) }}"
#          os: "{{ os | default(omit) }}"
#          host_name: "{{ inventory_hostname }}"
#      delegate_to: localhost