---
- name: Remove ServiceNow CMDB Record
  hosts: localhost
  gather_facts: no
  tasks:

    - name: CMDB data
      set_fact:
        cmdb_data:
          name: "{{ item }}"
          fqdn: "{{ item }}"
          ip_address: "{{ ansible_default_ipv4.address | default(omit) }}"
          os: "Red Hat Enterprise Linux"
          u_application: "web_app_1"
          install_status: "1"  # Installed
      loop: "{{ vm_names }}"

    - name: Print example of cmdb update module
      debug:
        msg: |
          Example task updating cmdb record:
          - name: Remove SNOW CMDB Record
            servicenow.itsm.configuration_item:
              state: absent
              asset_tag: "{{ '{{ owner | default(omit) }}' }}"
              name: "{{ '{{ inventory_hostname }}' }}"
              ip_address: "{{ '{{ ip_addr | default(omit) }}' }}"
              sys_class_name: cmdb_ci_server
              sys_id: "{{ '{{ sys_id | default(omit) }}' }}"
              other:
                classification: "{{ '{{ env | default(omit) }}' }}"
                fqdn: "{{ '{{ fqdn | default(omit) }}' }}"
                os: "{{ '{{ os | default(omit) }}' }}"
                host_name: "{{ '{{ inventory_hostname }}' }}"
            delegate_to: localhost