---
- name: Solution 1 - Add Job Templates
  hosts: all
  gather_facts: false
  vars_files:
    - ../vault.yml
    - vars/setup.yml
  connection: local
  tasks:
    - name: show vars
      ansible.builtin.debug:
        msg: |
          {{ aap_hostname }}
          {{ aap_username }}
          {{ aap_password }}

    - name: Call dispatch role
      ansible.builtin.include_role:
        name: infra.aap_configuration.dispatch
...