---
- name: Solution 1 - Add Job Templates
  hosts: all
  gather_facts: false
#  vars_files:
#    - ../vault.yml
  connection: local
  tasks:
    - name: Add all job templates needed for future exercises
      ansible.builtin.include_role:
        name: solution1_jts
...