---
- name: Solution 1 - Add Job Templates
  hosts: all
  gather_facts: false
  vars_files:
    - ../vault.yml
    - vars/solution1.yml
  connection: local
  tasks:
    - name: show vars
      ansible.builtin.debug:
        msg: |
          {{ lookup('ansible.builtin.env', 'CONTROLLER_HOST') }}
          {{ lookup('ansible.builtin.env', 'CONTROLLER_USERNAME') }}
          {{ lookup('ansible.builtin.env', 'CONTROLLER_PASSWORD') }}
          {{ aap_hostname }}
          {{ aap_username }}
          {{ aap_password }}

    - name: Call dispatch role
      ansible.builtin.include_role:
        name: infra.aap_configuration.dispatch
      vars:
        aap_hostname: "{{ lookup('ansible.builtin.env', 'CONTROLLER_HOST') }}"
        aap_username: "{{ lookup('ansible.builtin.env', 'CONTROLLER_USERNAME') }}"
        aap_password: "{{ lookup('ansible.builtin.env', 'CONTROLLER_PASSWORD') }}"
        controller_hostname: "{{ lookup('ansible.builtin.env', 'CONTROLLER_HOST') }}"
...